### ISSUE TITLE
Kernel-7.0.1 boot to selection fails

### ISSUE THREAD

**Issue by rmstrait** [OpenMediaVault-Plugin-Developers/openmediavault-kernel#5]
After installing the kernel plugin for OpenMediaVault 7.0-7 (Sandworm) and installing GParted Live from the Gui, I selected "Reboot to GParted Live once" and rebooted OMV.  This error message was displayed on the monitor after the reboot.
`Booting GParted Live
error: out of memory
error: no server was specified.
error: you need to load the kernel first.

Press any key to continue....`

After this, the blue Grub selection screen was displayed and waited for me to make a selection to boot to. I tried other kernel boot selections like Clonezilla Live from the OMV Gui with the same error messages. displayed after reboot.

My system info...
Hostname beelink.localdomain
Version 7.0-7 (Sandworm)
Processor Intel(R) N95
Kernel Linux 6.1.0-13-amd64
System Time 11/19/2023, 6:44:01 PM
Uptime 39 minutes
Load Average 0.48, 0.21, 0.08
Memory Usage 8.4% of 7.54 GiB

**Comment by ryecoaaron** [comment]
These errors are specific to your system.  Do you have secure boot enabled.

**Comment by rmstrait** [comment]
Secure boot was disabled.

I verified that with this same hardware and Bios settings the OMV 6 Kernel plugin was working properly.

**Comment by ryecoaaron** [comment]
I wasn't suggesting you enable it.  I just wanted to make sure it wasn't enabled.

The OMV 6.x and 7.x openmediavault-kernel plugins do the exact same thing.  I made no changes to how they configure grub.

Not really sure what causes this since I can't replicate it.  It is debian 12 grub issue but I don't know what it is.  Quite a few things I have seen mention reducing the video memory size in the bios and/or disabling IOMMU or lowering the GFX_MODE in grub.  I can't do anything about the video memory size in the plugin and the other options don't seem to have a good generic setting that would be good for all systems.  All I can suggest is possibly playing with the options in /etc/grub.d/42_gpartedlive or /etc/grub.d/42_clonezilla (run update-grub after changing settings) and see if you can get something to work.

**Comment by rmstrait** [comment]
Thank you.  I will try adjusting the things you suggested and see if I can get it to work.

**Comment by ryecoaaron** [comment]
Please let me know what you find.  Maybe I can change to the plugin to help.

**Comment by rmstrait** [comment]
I found that adding the option 
`rmmod tpm` to  the grub entry file makes it load and I get no errors. This works for Clonezilla Live but GParted hangs while loading at `i915 0000.00.02.0: [drm] VT-d active for gfx access`. I suppose I need another option to get GParted to work.

**Comment by ryecoaaron** [comment]
rmmod tpm seems safe to do on all systems.  I will look more into it and test on my systems.

**Comment by ryecoaaron** [comment]
rmmod tpm fails and causes an error on systems without tpm.
I improved the graphics mode for clonezilla that might fix issues.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-kernel/commit/15e7ea62630d6797442a61fe558b4cc9a3781182

I haven't found anything to help on gparted but I also haven't been able to reproduce on any of my systems.

**Comment by rmstrait** [comment]
Thanks. 

Removed `rmmod tpm` and replaced `vga=788` with  `gfxpayload=text` That fixes fixes my issue for Clonezilla.
